### ISSUE TITLE
Project TODO list

### ISSUE THREAD

**Issue by nkmathew** [nkmathew/GDICanvas#1]
- [x] CMake build file
- [ ] Try building with Clang
- [ ] Make it compile in Visual Studio 2013
